# Generated by Django 5.0.6 on 2024-06-17 18:24

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accidents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("spend_money", models.DecimalField(decimal_places=2, max_digits=6)),
                ("more_info", models.TextField()),
                (
                    "prove",
                    models.FileField(
                        upload_to="accidents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "docx", "txt", "xls"],
                                message="Fayl formati to'g'riga o'xshamaydi",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Baxtsiz hodisa",
                "verbose_name_plural": "Baxtsiz hodisalar",
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField()),
                (
                    "status_application",
                    models.CharField(
                        choices=[
                            ("Y", "Yuborilgan"),
                            ("R", "O'qilgan"),
                            ("RJ", "Rad etilgan"),
                        ],
                        default="Y",
                        max_length=128,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ariza",
                "verbose_name_plural": "Arizalar",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100, unique=True)),
                ("spend_money", models.DecimalField(decimal_places=0, max_digits=9)),
                (
                    "description",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                100, message="Ilitmos ko'proq ma'lumot kiriting"
                            )
                        ]
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="event/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "png",
                                    "jpg",
                                    "jpeg",
                                    "webp",
                                    "avif",
                                ]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Tadbir",
                "verbose_name_plural": "Tadbirlar",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        max_length=256,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                5, message="Tashkilot nomini to'liqroq yozing"
                            )
                        ],
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="UZ", unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="organization/images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "png",
                                    "jpg",
                                    "jpeg",
                                    "webp",
                                    "avif",
                                ],
                                message="Faqat rasm yuklashingiz mumkin (png, jpg, jpeg, webp, avif) formatlarida",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                150, "Ilitmos tashkilot haqida ko'proq ma'lumot bering!"
                            )
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "Tashkilot",
                "verbose_name_plural": "Tashkilotlar",
            },
        ),
        migrations.CreateModel(
            name="SpiritualRest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=512)),
                (
                    "description",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                100, message="Iltimos ko'proq ma'lumot kiriting !"
                            )
                        ]
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="spirtual_rest/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "webp"],
                                message="Iltimos faqat rasm yuklang",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Ma'naviy dam olish",
                "verbose_name_plural": "Ma'naviy dam olishlar",
            },
        ),
    ]
