# Generated by Django 5.0.6 on 2024-06-14 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_staffs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='staffs',
        ),
        migrations.AddField(
            model_name='organization',
            name='staffs',
            field=models.ManyToManyField(related_name='staffs_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
