# Generated by Django 5.0.6 on 2024-06-14 17:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_oranization'),
        ('organization', '0003_remove_organization_staffs_organization_staffs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='id_cards',
            field=models.CharField(default='AD1460165', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=1)),
                ('spend_money', models.PositiveBigIntegerField(default=0)),
                ('more_info', models.TextField()),
                ('prove', models.FileField(upload_to='prove/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'dosx', 'txt', 'xls'], message="Fayl formati to'g'riga o'xshamaydi")])),
                ('who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Y', 'Yuborilgan'), ('R', "O'qilgan"), ('RJ', 'Rad etilgan')], default='Y', max_length=2)),
                ('who_are_viewed', models.ManyToManyField(related_name='application_viwed_staffs', to='employee.employee')),
                ('who_rejected', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(verbose_name=django.core.validators.MinLengthValidator(100, message="Iltimos ko'proq ma'lumot kiriting"))),
                ('author_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('status_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.applicationstatusmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('spend_money', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(100, message="Ilitmos ko'proq ma'lumot kiriting")])),
                ('image', models.ImageField(upload_to='event/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'avif'])])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpiritualRest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('more_info', models.TextField(validators=[django.core.validators.MinLengthValidator(100, message="Iltimos ko'proq ma'lumot kiriting !")])),
                ('image', models.ImageField(upload_to='spirtual_rest/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'], message='Iltimos faqat rasm yuklang')])),
                ('additional_doc', models.FileField(blank=True, null=True, upload_to='additional_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'dosx', 'txt', 'xls'], message="Fayl formati to'g'riga o'xshamaydi")])),
                ('who_are_invited', models.ManyToManyField(related_name='spirtual_rest_person', to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
