# Generated by Django 5.0.6 on 2024-06-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_id_cards_accidents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='id_cards',
        ),
        migrations.AddField(
            model_name='organization',
            name='id_cards',
            field=models.ManyToManyField(related_name='employee_id_card', to='organization.idcards'),
        ),
    ]
