# Generated by Django 5.0.6 on 2024-06-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_idcards_remove_organization_id_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcards',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
