# Generated by Django 5.0.6 on 2024-06-14 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_remove_accidents_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidents',
            name='prove',
            field=models.FileField(upload_to='prove/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt', 'xls'], message="Fayl formati to'g'riga o'xshamaydi")]),
        ),
    ]
