# Generated by Django 5.0.6 on 2024-06-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_accidents_prove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='body',
            field=models.TextField(),
        ),
    ]
