# Generated by Django 5.0.6 on 2024-06-16 05:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandicappedDocsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='docs/handicapped/')),
                ('type', models.CharField(choices=[('S', "Sog'lom"), ('I', 'Ikkinchi gurux nogironi'), ('U', 'Uchinchi gurux nogironi')], default='S', max_length=1)),
            ],
            options={
                'verbose_name': 'Nogironlik haqidagi hujjat',
                'verbose_name_plural': 'Nogironlik haqidagi hujjatlar',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Ish turi',
                'verbose_name_plural': 'Ish turlari',
            },
        ),
        migrations.CreateModel(
            name='RoleNoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='docs/role/')),
                ('type', models.CharField(choices=[('Y', "Yo'q"), ('A', 'Ayollar daftari'), ('T', 'Temir daftar')], default='Y', max_length=1)),
            ],
            options={
                'verbose_name': 'Daftar',
                'verbose_name_plural': 'Daftarlar',
            },
        ),
        migrations.CreateModel(
            name='UnderAgeChildren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='docs/under_age_children/')),
            ],
            options={
                'verbose_name': 'Voyaga yetmagan farzand hujjati',
                'verbose_name_plural': 'Voyaga yetmagan farzandlar hujjatlari',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oranization', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('E', 'Erkak'), ('A', 'Ayol')], default='E', max_length=1)),
                ('tel_number', models.CharField(max_length=18, unique=True)),
                ('id_card', models.CharField(max_length=9, unique=True)),
                ('born_in', models.DateField()),
                ('employment_at', models.DateField()),
                ('under_age_children_number', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6, message="Iltimos to'g'ri kiriting !")])),
                ('salary', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('allocated_funds', models.PositiveBigIntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_user', to=settings.AUTH_USER_MODEL)),
                ('handicapped', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handicapped_person', to='employee.handicappeddocsmodel')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.job')),
                ('role', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_note', to='employee.rolenotemodel')),
                ('under_age_children_docs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.underagechildren')),
            ],
            options={
                'verbose_name': 'Ishchi',
                'verbose_name_plural': 'Ishchilar',
            },
        ),
    ]
