# Generated by Django 5.0.6 on 2024-06-14 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_under_age_children_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='handicapped',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handicapped_person', to='employee.handicappeddocsmodel'),
        ),
    ]
