# Generated by Django 5.0.6 on 2024-06-14 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='under_age_children_docs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.underagechildren'),
        ),
    ]
