# Generated by Django 5.0.6 on 2024-06-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_under_age_children_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='oranization',
            field=models.CharField(max_length=256),
        ),
    ]
