# Generated by Django 5.0.6 on 2024-06-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_oranization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolenotemodel',
            options={'verbose_name': 'Daftar', 'verbose_name_plural': 'Daftarlar'},
        ),
    ]
